# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/convertbot/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/frontend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/models/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/mq/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/shared/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/slackbot/"
    schedule:
      interval: "daily"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/packages/convertbot/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/packages/slackbot/"
    schedule:
      interval: "daily"
