name: Publish Docker image
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            expediagroup/insights-explorer
          tags: |
            type=ref,event=pr
            type=ref,event=branch

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


